#!/bin/bash

if [ `which quilt` ]; then
   echo; echo 'Using quilt'; echo
   quilt push -a
else
   echo; echo 'WARNING: Not using quilt, not suitable for dev environment';
   echo;
   PS_DIR=$PWD
   (cd patches; cat `cat series`) | patch -p1 -d $PS_DIR
fi

