usr/lib/mysql/plugin/authentication_ldap_sasl_client.so
usr/lib/mysql/plugin/authentication_kerberos_client.so
usr/lib/mysql/plugin/authentication_webauthn_client.so
usr/lib/mysql/plugin/authentication_openid_connect_client.so
usr/lib/mysql/plugin/authentication_oci_client.so
usr/lib/mysql/plugin/mysql_native_password.so
usr/lib/mysql/plugin/dialog.so
usr/lib/mysql/private/libfido2.so.*
# debug variants
usr/lib/mysql/plugin/debug/authentication_ldap_sasl_client.so
usr/lib/mysql/plugin/debug/authentication_kerberos_client.so
usr/lib/mysql/plugin/debug/authentication_webauthn_client.so
usr/lib/mysql/plugin/debug/authentication_openid_connect_client.so
usr/lib/mysql/plugin/debug/authentication_oci_client.so
usr/lib/mysql/plugin/debug/mysql_native_password.so
usr/lib/mysql/plugin/debug/dialog.so
