# Configuration files
debian/extra/mysql.cnf  etc/mysql/
debian/extra/mysqld.cnf /etc/mysql/mysql.conf.d/

# AppArmor profile
debian/extra/apparmor.d/usr.sbin.mysqld.in2 etc/apparmor.d/
debian/extra/apparmor.d/old_apparmor etc/apparmor.d/
debian/extra/apparmor.d/local/usr.sbin.mysqld.in etc/apparmor.d/local/

# Service support files
usr/share/mysql/mysql-helpers
usr/share/mysql/mysql-systemd-start
usr/share/mysql/mysqld_multi.server

# Telemetry helper scripts
debian/extra/percona-telemetry-setup.sh usr/libexec/percona-server/
debian/extra/percona-telemetry-cleanup.sh usr/libexec/percona-server/

# Defaults file
etc/default/mysql
