#!/bin/bash -e

# Some postinstall info about RocksDB
if [ -z "$2" ]; then
	echo -e "\n\n * This release of Percona Server is distributed with RocksDB storage engine."
	echo -e " * Run the following script to enable the RocksDB storage engine in Percona Server:\n"
	echo -e "\tps-admin --enable-rocksdb -u <mysql_admin_user> -p[mysql_admin_pass] [-S <socket>] [-h <host> -P <port>]\n\n"
fi

#DEBHELPER#
exit 0
