# binaries
usr/bin/comp_err
usr/bin/myisamchk
usr/bin/myisamlog
usr/bin/myisampack
usr/bin/my_print_defaults
usr/bin/mysql_secure_installation
usr/bin/mysql_ssl_rsa_setup
usr/bin/mysql_tzinfo_to_sql
usr/bin/mysql_upgrade
usr/bin/mysqlbinlog
usr/bin/mysqld_multi
usr/bin/mysqld_safe
usr/bin/ps_mysqld_helper
usr/bin/perror
usr/sbin/mysqld
usr/bin/ps-admin
usr/bin/ibd2sdi
usr/bin/mysql_migrate_keyring

# configuration files
debian/extra/mysql.cnf  etc/mysql/
debian/extra/mysqld.cnf /etc/mysql/mysql.conf.d/

# AppArmor profile
debian/extra/apparmor.d/usr.sbin.mysqld.in etc/apparmor.d/
debian/extra/apparmor.d/local/usr.sbin.mysqld.in etc/apparmor.d/local/

# debug binary
usr/sbin/mysqld-debug
# man pages
usr/share/man/man1/comp_err.1
usr/share/man/man1/myisamchk.1
usr/share/man/man1/myisamlog.1
usr/share/man/man1/myisampack.1
usr/share/man/man1/my_print_defaults.1
usr/share/man/man1/mysql_secure_installation.1
usr/share/man/man1/mysql_ssl_rsa_setup.1
usr/share/man/man1/mysql_tzinfo_to_sql.1
usr/share/man/man1/mysql_upgrade.1
usr/share/man/man1/mysqlbinlog.1
usr/share/man/man1/mysqld_multi.1
usr/share/man/man1/mysqld_safe.1
usr/share/man/man1/mysql.server.1
usr/share/man/man1/ibd2sdi.1
usr/share/man/man1/perror.1
usr/share/man/man8/mysqld.8
# SQL files
usr/share/mysql/*.sql
#private shared libs
usr/lib/mysql/private/libprotobuf-lite.so.*
usr/lib/mysql/private/libprotobuf.so.*
usr/lib/mysql/private/libfido2.so.*
# private data files
usr/lib/mysql/private/icudt69l/unames.icu
usr/lib/mysql/private/icudt69l/brkitr/*
# plugins
usr/lib/mysql/plugin/adt_null.so
usr/lib/mysql/plugin/auth_socket.so
usr/lib/mysql/plugin/innodb_engine.so
usr/lib/mysql/plugin/libmemcached.so
usr/lib/mysql/plugin/libpluginmecab.so
usr/lib/mysql/plugin/locking_service.so
usr/lib/mysql/plugin/mypluglib.so
usr/lib/mysql/plugin/mysql_no_login.so
usr/lib/mysql/plugin/rewriter.so
usr/lib/mysql/plugin/semisync_master.so
usr/lib/mysql/plugin/semisync_slave.so
usr/lib/mysql/plugin/test_security_context.so
usr/lib/mysql/plugin/validate_password.so
usr/lib/mysql/plugin/version_token.so
usr/lib/mysql/plugin/connection_control.so
usr/lib/mysql/plugin/keyring_file.so
usr/lib/mysql/plugin/keyring_udf.so
usr/lib/mysql/plugin/component_log_filter_dragnet.so
usr/lib/mysql/plugin/component_log_sink_json.so
usr/lib/mysql/plugin/component_log_sink_syseventlog.so
usr/lib/mysql/plugin/component_validate_password.so
usr/lib/mysql/plugin/component_audit_api_message_emit.so
usr/lib/mysql/plugin/component_query_attributes.so
usr/lib/mysql/plugin/component_test_udf_services.so
usr/lib/mysql/plugin/component_reference_cache.so
usr/lib/mysql/plugin/component_keyring_file.so
usr/lib/mysql/plugin/mysql_clone.so
usr/lib/mysql/plugin/data_masking.*
usr/lib/mysql/plugin/component_mysqlbackup.so
usr/lib/mysql/plugin/debug/component_mysqlbackup.so
usr/lib/mysql/plugin/debug/data_masking.so
usr/lib/mysql/plugin/debug/mysql_clone.so
usr/lib/mysql/plugin/debug/adt_null.so
usr/lib/mysql/plugin/debug/auth_socket.so
usr/lib/mysql/plugin/debug/innodb_engine.so
usr/lib/mysql/plugin/debug/libmemcached.so
usr/lib/mysql/plugin/debug/libpluginmecab.so
usr/lib/mysql/plugin/debug/locking_service.so
usr/lib/mysql/plugin/debug/mypluglib.so
usr/lib/mysql/plugin/debug/mysql_no_login.so
usr/lib/mysql/plugin/debug/rewriter.so
usr/lib/mysql/plugin/debug/semisync_master.so
usr/lib/mysql/plugin/debug/semisync_slave.so
usr/lib/mysql/plugin/debug/test_security_context.so
usr/lib/mysql/plugin/debug/validate_password.so
usr/lib/mysql/plugin/debug/version_token.so
usr/lib/mysql/plugin/debug/keyring_file.so
usr/lib/mysql/plugin/debug/keyring_udf.so
usr/lib/mysql/plugin/debug/connection_control.so
usr/lib/mysql/plugin/debug/group_replication.so
usr/lib/mysql/plugin/debug/authentication_ldap_sasl_client.so
usr/lib/mysql/plugin/debug/component_test_udf_services.so
usr/lib/mysql/plugin/debug/component_query_attributes.so
usr/lib/mysql/plugin/debug/component_test_component_deinit.so
usr/lib/mysql/plugin/debug/component_reference_cache.so
usr/lib/mysql/plugin/debug/component_keyring_file.so
usr/lib/mysql/plugin/debug/authentication_kerberos_client.so
usr/lib/mysql/plugin/debug/component_test_table_access.so
usr/lib/mysql/plugin/debug/component_test_mysql_system_variable_set.so
usr/lib/mysql/plugin/debug/semisync_replica.so
usr/lib/mysql/plugin/debug/semisync_source.so
usr/lib/mysql/plugin/debug/authentication_fido_client.so

# Percona plugins
usr/lib/mysql/plugin/audit_log.so
usr/lib/mysql/plugin/debug/audit_log.so
usr/lib/mysql/plugin/auth_pam.so
usr/lib/mysql/plugin/debug/auth_pam.so
usr/lib/mysql/plugin/auth_pam_compat.so
usr/lib/mysql/plugin/debug/auth_pam_compat.so
usr/lib/mysql/plugin/libfnv1a_udf.so
usr/lib/mysql/plugin/debug/libfnv1a_udf.so
usr/lib/mysql/plugin/libfnv_udf.so
usr/lib/mysql/plugin/debug/libfnv_udf.so
usr/lib/mysql/plugin/libmurmur_udf.so
usr/lib/mysql/plugin/debug/libmurmur_udf.so
usr/lib/mysql/plugin/dialog.so
usr/lib/mysql/plugin/debug/dialog.so
usr/lib/mysql/plugin/connection_control.so
usr/lib/mysql/plugin/group_replication.so
usr/lib/mysql/plugin/authentication_ldap_sasl_client.so
usr/lib/mysql/plugin/debug/keyring_vault.so
usr/lib/mysql/plugin/keyring_vault.so
usr/lib/mysql/plugin/authentication_ldap_simple.so
usr/lib/mysql/plugin/component_test_component_deinit.so
usr/lib/mysql/plugin/binlog_utils_udf.so
usr/lib/mysql/plugin/test_udf_wrappers.so
usr/lib/mysql/plugin/debug/binlog_utils_udf.so
usr/lib/mysql/plugin/debug/test_udf_wrappers.so
usr/lib/mysql/plugin/procfs.so
usr/lib/mysql/plugin/debug/procfs.so
usr/lib/mysql/plugin/authentication_kerberos_client.so
usr/lib/mysql/plugin/semisync_replica.so
usr/lib/mysql/plugin/semisync_source.so
usr/lib/mysql/plugin/component_test_table_access.so
usr/lib/mysql/plugin/component_test_mysql_system_variable_set.so
usr/lib/mysql/plugin/authentication_oci_client.so
usr/lib/mysql/plugin/component_keyring_kmip.so
usr/lib/mysql/plugin/debug/authentication_oci_client.so
usr/lib/mysql/plugin/debug/component_keyring_kmip.so
usr/lib/mysql/plugin/authentication_fido_client.so
usr/lib/mysql/plugin/component_encryption_udf.so
usr/lib/mysql/plugin/debug/component_encryption_udf.so
usr/lib/mysql/plugin/component_keyring_kms.so
usr/lib/mysql/plugin/debug/component_keyring_kms.so
usr/lib/mysql/plugin/authentication_fido.so
usr/lib/mysql/plugin/debug/authentication_fido.so
usr/lib/mysql/plugin/authentication_ldap_sasl.so
usr/lib/mysql/plugin/debug/authentication_ldap_sasl.so

# support files
usr/share/mysql/dictionary.txt
usr/share/mysql/mysql-log-rotate
usr/share/mysql/mysql-helpers
usr/share/mysql/mysql-systemd-start
usr/share/mysql/mysqld_multi.server
# defaults file
etc/default/mysql
